sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucket-name: sky-take-out-for-aster
    region: cn-chengdu
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10