sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tR4Qf85uy6E2yqWUVAu
    access-key-secret: 6s1rTIafa7nHlLaO65vemiFgEjg6bQ
    bucket-name: sky-take-out-for-aster